### ISSUE TITLE
S3 - 💚  DEPLOY

### ISSUE THREAD

**Issue by marinamassaneiro** [kabianca/social-network#16]
Fazer deploy do aplicativo e marcar a versão (git tag).

**Comment by kabianca** [comment]
Instalei a dependencia gh-pages com:

`npm i gh-pages`

Inseri no package.json o script:

`"deploy": "gh-pages -d src"`

Isso criou uma branch no projeto chamada gh-pages. Essa branch contém os arquivos da src e assume o papel de pasta raiz no deploy e, assim, o endereço do index é lido de forma correta.
