### ISSUE TITLE
S4 - 💛 -  Pré-escrita testes (chamada erros) - Fase 1

### ISSUE THREAD

**Issue by marinamassaneiro** [kabianca/social-network#25]
Limpar/corrigir código para chegar no teste efetivamente:
 - [x] rodar "npm t" e corrigir pequenos detalhes de escrita;
 - [x] corrigir/chamar os erros corretamente dentro das funções do Firebase: arquivo Register.js;
 - [x] corrigir/chamar os erros corretamente dentro das funções do Firebase: arquivo Login.js;
 - [x] corrigir import Firebase: arquivo Config.js;
 - [x] corrigir import Firebase: arquivo Auth.js;
 - [x] chamar/usar as variáveis que não estão sendo chamadas;

**Comment by kabianca** [comment]
O import do firebase foi corrigido com a inserção de um comentário que desabilita o eslint em uma linha específica. Pode não ser a melhor solução (vamos ficar atentas a outras, especialmente para de usar o link), mas vai ajudar a avançar por enquanto.

`//eslint-disable-line`
