### ISSUE TITLE
S4 - 💛  - Versão Desktop - História 1

### ISSUE THREAD

**Issue by marinamassaneiro** [kabianca/social-network#26]
- [x] Prototipar as telas (login, cadastro e timeline) para desktop no figma;
- [x] Aplicar no CSS as características da versão desktop: login;
- [x] Aplicar no CSS as características da versão desktop: cadastro;
- [x] Aplicar no CSS as características da versão desktop: timeline;
- [x] Trabalhar responsividade (flexbox, zoom...);

**Comment by polyanagm** [comment]
Mantive o ícone do Home e Logout no lugar do nome escrito, pois o escrito estava dando erro.
