### ISSUE TITLE
S5 - ❤ - Armazenar Posts - Firestore

### ISSUE THREAD

**Issue by kabianca** [kabianca/social-network#35]
- [x] Criar um arquivo para os dados de configuração do firestore;
- [x] Criar um arquivo com as funções do firestore e exportá-las;
- [x] Criar campos de input para postagem na timeline;
- [x] Criar botão para submeter o post;
- [x] Inserir as postagens dos usuário na base de dados do Firestore;

**Comment by kabianca** [comment]
Cada uma tenta trazer uma proposta de código com o firestore funcionando (coletando post de usuários e armazenação na coleção). 

**Deadline**: 30 de setembro (sexta-feira).

**Comment by marinamassaneiro** [comment]
Todas conseguimos armazenar no Firestore até o dia 30/09. Karla conseguiu avançar um pouco mais com a impressão d objeto dos dados na tela e Marina conseguiu avançar um pouco mais no template dos inputs e impressao do post.
