### ISSUE TITLE
S6 - 💛 - Timeline - Publicar Post

### ISSUE THREAD

**Issue by kabianca** [kabianca/social-network#41]
- [x] Input para usuário;
- [x] Conseguir publicar um post;
- [x] Puxar dados do documento de post na coleção do Firestore;
- [x] Imprimir na timeline o post dos usuários ao iniciar;
- [x] Ao recarregar o aplicativo, é necessário verificar se o usuário está logado antes de exibir o conteúdo.
- [ ] Ao publicar, deve ser validado se há conteúdo no input.

**Comment by marinamassaneiro** [comment]
To em duvida se a gente faz erro pra cada imput como no register, posso fazer sem problemansss. Mas me perguntei se era isso ou o que já temos de recipe !== ''.
